apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/elalejmartin/ArgoTest.git'
    targetRevision: master
    path: k8s/Microservices2
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
