apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservicio2
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/elalejmartin/ArgoTest.git'
    targetRevision: master
    path: Microservices2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
