apiVersion: v1
kind: Service
metadata:
  name: microservice-1
spec:
  selector:
    app: microservice-1
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30081 # puerto entre 30000-32767
  type: NodePort
